### PR TITLE
fix #669: dmledit crash on resize

### LINKED ISSUE #669: DMLEdit crashes on resizing things

### PR DESCRIPTION
**Pull request by xucs007**

### CODE REVIEW

File: src/dlangui/widgets/layouts.d [hunk 1]
```diff
@@ -519,10 +519,14 @@ class ResizerWidget : Widget {
     private void resizeAndFireEvent(short newWidth, ResizerEventType type)
     {
         // Respect the dimensions
-        if(newWidth > minPreviousItemWidth && newWidth < (parent.width - minWidth - minNextItemWidth) &&
-           newWidth > _previousWidget.minWidth() && newWidth < (parent.width - minWidth - _nextWidget.minWidth()))
+        if( (newWidth > minPreviousItemWidth) && (newWidth < (parent.width - minWidth - minNextItemWidth)) && (_previousWidget is null ||
```
Comment (GrimMaple) [inline src/dlangui/widgets/layouts.d:522]: Is it intended to be `_previousWidget is null` ? Appears like you meant `!is null` instead

**Review by GrimMaple — CHANGES_REQUESTED** [review]

File: src/dlangui/widgets/layouts.d (hunk 1 above)
Comment (xucs007) [reply src/dlangui/widgets/layouts.d:522]: _previousWidget can be null -- at least true for dmledit resizing.

Comment (GrimMaple) [reply src/dlangui/widgets/layouts.d:522]: Oh yea, I see what you did there now!
